"""Add feedback column tothe chat_messages

Revision ID: 0d45d899a58c
Revises: 1bcfa4566e29
Create Date: 2026-03-06 14:44:46.745805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d45d899a58c'
down_revision: Union[str, Sequence[str], None] = '1bcfa4566e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('feedback', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'feedback')
    # ### end Alembic commands ###
