"""initial_schema

Revision ID: 0f74e2e215f6
Revises:
Create Date: 2026-04-10 12:13:31.467894

"""

from collections.abc import Sequence

import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0f74e2e215f6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("api_key", sa.String(), nullable=False),
        sa.Column("is_superadmin", sa.Boolean(), nullable=False),
        sa.Column("max_bots", sa.Integer(), server_default="100", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("reset_otp", sa.String(), nullable=True),
        sa.Column("reset_otp_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("bot_name", sa.String(), nullable=True),
        sa.Column("bot_logo", sa.Text(), nullable=True),
        sa.Column("launcher_name", sa.String(), nullable=True),
        sa.Column("launcher_logo", sa.Text(), nullable=True),
        sa.Column("primary_color", sa.String(), nullable=True),
        sa.Column("background_color", sa.String(), nullable=True),
        sa.Column("header_color", sa.String(), nullable=True),
        sa.Column("recommended_colors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_api_key"), "clients", ["api_key"], unique=True)
    op.create_index(op.f("ix_clients_email"), "clients", ["email"], unique=True)
    op.create_table(
        "bots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("bot_key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), server_default="AI Assistant", nullable=True),
        sa.Column("system_prompt", sa.Text(), nullable=True),
        sa.Column("brand_tone", sa.Text(), nullable=True),
        sa.Column("company_name", sa.String(), nullable=True),
        sa.Column("company_description", sa.Text(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("bot_logo", sa.Text(), nullable=True),
        sa.Column("launcher_name", sa.String(), server_default="Have Questions?", nullable=True),
        sa.Column("launcher_logo", sa.Text(), nullable=True),
        sa.Column("primary_color", sa.String(), server_default="#ba68c8", nullable=True),
        sa.Column("background_color", sa.String(), server_default="#ffffff", nullable=True),
        sa.Column("header_color", sa.String(), server_default="#3A0CA3", nullable=True),
        sa.Column("recommended_colors", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("user_bubble_color", sa.String(), server_default="#DBE9FF", nullable=True),
        sa.Column("bant_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("bant_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("avatar_type", sa.String(), server_default="upload", nullable=False),
        sa.Column("orb_color", sa.String(), nullable=True),
        sa.Column("lead_form_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("lead_form_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("notification_email", sa.String(), nullable=True),
        sa.Column("notification_emails", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("reply_to_email", sa.String(), nullable=True),
        sa.Column("email_on_qualified", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email_on_handoff", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email_on_offline", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("email_visitor_confirmation", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("live_chat_enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("operator_timeout_seconds", sa.Integer(), server_default="120", nullable=False),
        sa.Column("visitor_disconnect_timeout", sa.Integer(), server_default="120", nullable=False),
        sa.Column("operator_disconnect_timeout", sa.Integer(), server_default="60", nullable=False),
        sa.Column("business_hours", sa.JSON(), nullable=True),
        sa.Column("welcome_title", sa.String(), server_default="Hi there 👋", nullable=False),
        sa.Column("welcome_subtitle", sa.String(), server_default="How can we help you today?", nullable=False),
        sa.Column("waiting_message", sa.String(), server_default="Connecting you to support...", nullable=False),
        sa.Column("offline_message", sa.String(), server_default="Our team is currently unavailable.", nullable=False),
        sa.Column("handoff_delay_seconds", sa.Integer(), server_default="0", nullable=False),
        sa.Column("calendly_url", sa.String(), nullable=True),
        sa.Column("meeting_booking_enabled", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "feature_flags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"file_sharing": false, "post_chat_rating": true, "show_branding": true, "queue_position": false, "typing_preview": true, "email_transcript": false}',
            nullable=False,
        ),
        sa.Column(
            "widget_messages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"welcome_greeting": "Hi There, How can I help you today?", "welcome_suggestions": ["Our Services", "About us", "Contact us"], "input_placeholder": "Write a message...", "live_chat_label": "Live chat", "greeting_message": "Hi! Let us know if you have any questions.", "offline_message": "Team is currently unavailable", "rating_prompt": "How was your experience?", "end_chat_label": "End chat and return to AI"}',
            nullable=False,
        ),
        sa.Column(
            "widget_config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='{"welcome_exit_duration_ms": 350, "greeting_delay_ms": 3000, "typing_timeout_ms": 2000, "frustration_window_ms": 30000, "frustration_threshold_messages": 3, "max_reconnect_attempts": 15, "max_reconnect_delay_ms": 30000, "heartbeat_visible_ms": 25000, "heartbeat_hidden_ms": 50000, "handoff_auto_submit_delay_ms": 300}',
            nullable=False,
        ),
        sa.Column("branding_text", sa.String(), server_default="Powered by OyeChats", nullable=False),
        sa.Column("branding_url", sa.String(), server_default="https://oyechats.com", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bots_bot_key"), "bots", ["bot_key"], unique=True)
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bot_growth_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.CheckConstraint(
            "event_type IN ('demo_share_clicked', 'demo_link_opened')", name="ck_bot_growth_events_event_type"
        ),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bot_growth_events_bot_id"), "bot_growth_events", ["bot_id"], unique=False)
    op.create_table(
        "documents",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("bot_id", sa.Integer(), nullable=True),
        sa.Column("document_name", sa.String(), nullable=False),
        sa.Column("file_hash", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("embedding", Vector(1536), nullable=False),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_documents_file_hash"), "documents", ["file_hash"], unique=False)
    op.create_index("ix_documents_search_vector", "documents", ["search_vector"], unique=False, postgresql_using="gin")
    op.create_table(
        "operators",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("is_online", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("operator_api_key", sa.String(), nullable=True),
        sa.Column("role", sa.String(), server_default="operator", nullable=False),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("avatar_url", sa.String(), nullable=True),
        sa.Column("max_concurrent_chats", sa.Integer(), server_default="5", nullable=False),
        sa.Column("notification_preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_operators_operator_api_key"), "operators", ["operator_api_key"], unique=True)
    op.create_table(
        "webhooks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("secret", sa.String(), nullable=False),
        sa.Column("events", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhooks_bot_id"), "webhooks", ["bot_id"], unique=False)
    op.create_table(
        "canned_responses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("shortcut", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("created_by_operator_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["created_by_operator_id"], ["operators.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_sessions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("bot_id", sa.Integer(), nullable=True),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("device", sa.String(), nullable=True),
        sa.Column("behavioral_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("page_url", sa.String(), nullable=True),
        sa.Column("referrer", sa.String(), nullable=True),
        sa.Column("utm_params", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("visit_count", sa.Integer(), server_default="1", nullable=False),
        sa.Column("bant_need", sa.Text(), nullable=True),
        sa.Column("bant_timeline", sa.String(), nullable=True),
        sa.Column("bant_authority", sa.String(), nullable=True),
        sa.Column("bant_budget", sa.String(), nullable=True),
        sa.Column("bant_need_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bant_budget_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bant_authority_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bant_timeline_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bant_score", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bant_tier", sa.String(), server_default="unqualified", nullable=False),
        sa.Column("dimensions_assessed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("bant_last_updated", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dimension_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("qualification_framework", sa.String(), server_default="bant", nullable=False),
        sa.Column("status", sa.String(), server_default="bot", nullable=False),
        sa.Column("assigned_operator_id", sa.Integer(), nullable=True),
        sa.Column("handoff_reason", sa.Text(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("visitor_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("visitor_rating", sa.Integer(), nullable=True),
        sa.Column("visitor_resolved", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("last_active_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["assigned_operator_id"], ["operators.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("webhook_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("attempt", sa.Integer(), server_default="1", nullable=False),
        sa.Column("next_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["webhook_id"], ["webhooks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhook_deliveries_webhook_id"), "webhook_deliveries", ["webhook_id"], unique=False)
    op.create_table(
        "chat_audit_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["operator_id"], ["operators.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("feedback", sa.Integer(), nullable=True),
        sa.Column("trace_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lead_info",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_table(
        "meeting_bookings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("booking_url", sa.String(), nullable=True),
        sa.Column("meeting_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attendee_email", sa.String(), nullable=True),
        sa.Column("status", sa.String(), server_default="scheduled", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meeting_bookings_session_id"), "meeting_bookings", ["session_id"], unique=False)
    op.create_table(
        "offline_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=True),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.Column("visitor_name", sa.String(), nullable=False),
        sa.Column("visitor_email", sa.String(), nullable=False),
        sa.Column("visitor_phone", sa.String(), nullable=True),
        sa.Column("message_body", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), server_default="new", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["department_id"], ["departments.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "visitor_events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("bot_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("event_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["bot_id"], ["bots.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_visitor_events_session_id"), "visitor_events", ["session_id"], unique=False)
    op.create_table(
        "bant_signals",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=True),
        sa.Column("dimension", sa.String(), nullable=False),
        sa.Column("signal_text", sa.Text(), nullable=False),
        sa.Column("extracted_value", sa.Text(), nullable=True),
        sa.Column("confidence", sa.String(), server_default="medium", nullable=False),
        sa.Column("score_before", sa.Integer(), server_default="0", nullable=False),
        sa.Column("score_after", sa.Integer(), server_default="0", nullable=False),
        sa.Column("source", sa.String(), server_default="llm", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["chat_messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["session_id"], ["chat_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bant_signals_session_id"), "bant_signals", ["session_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bant_signals_session_id"), table_name="bant_signals")
    op.drop_table("bant_signals")
    op.drop_index(op.f("ix_visitor_events_session_id"), table_name="visitor_events")
    op.drop_table("visitor_events")
    op.drop_table("offline_messages")
    op.drop_index(op.f("ix_meeting_bookings_session_id"), table_name="meeting_bookings")
    op.drop_table("meeting_bookings")
    op.drop_table("lead_info")
    op.drop_table("chat_messages")
    op.drop_table("chat_audit_logs")
    op.drop_index(op.f("ix_webhook_deliveries_webhook_id"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_table("chat_sessions")
    op.drop_table("canned_responses")
    op.drop_index(op.f("ix_webhooks_bot_id"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index(op.f("ix_operators_operator_api_key"), table_name="operators")
    op.drop_table("operators")
    op.drop_index("ix_documents_search_vector", table_name="documents", postgresql_using="gin")
    op.drop_index(op.f("ix_documents_file_hash"), table_name="documents")
    op.drop_table("documents")
    op.drop_index(op.f("ix_bot_growth_events_bot_id"), table_name="bot_growth_events")
    op.drop_table("bot_growth_events")
    op.drop_table("departments")
    op.drop_index(op.f("ix_bots_bot_key"), table_name="bots")
    op.drop_table("bots")
    op.drop_index(op.f("ix_clients_email"), table_name="clients")
    op.drop_index(op.f("ix_clients_api_key"), table_name="clients")
    op.drop_table("clients")
    # ### end Alembic commands ###
