"""company_profile — cross-tenant domain → company cache

One row per registrable domain, shared across every tenant. It holds only
public web data about a company, so there is nothing to leak between
customers, and sharing means a popular domain is crawled once for the whole
platform rather than once per customer.

Failures are cached alongside successes (``resolution_failed`` +
``retry_after``) so a dead or parked domain costs a single crawl instead of one
per lead arriving from it.

The create is guarded: ``app/main.py`` calls ``Base.metadata.create_all()`` at
startup, so on any environment that has booted since the model landed the table
already exists and a bare ``op.create_table`` would fail the deploy. Same
pattern as ``a7f3c1e94b26``.

Revision ID: 1da557cae107
Revises: a7f3c1e94b26
Create Date: 2026-08-10 17:41:18.145112
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "1da557cae107"
down_revision: str | Sequence[str] | None = "a7f3c1e94b26"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "company_profile"


def _table_exists() -> bool:
    return sa.inspect(op.get_bind()).has_table(TABLE)


def upgrade() -> None:
    """Create the table if it does not already exist."""
    if _table_exists():
        # Already present (e.g. built by an earlier create_all run). No-op.
        return

    op.create_table(
        TABLE,
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("resolution_failed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("retry_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refresh_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("domain"),
    )


def downgrade() -> None:
    """Drop the table. Safe — it is a rebuildable cache, not a source of truth.

    Every row can be regenerated by re-crawling the domain, so losing it costs
    one crawl per domain rather than any real data.
    """
    if _table_exists():
        op.drop_table(TABLE)
