"""added logos column

Revision ID: 20a1e88dddcd
Revises: 6eb717126b3f
Create Date: 2026-03-17 15:37:47.815358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a1e88dddcd'
down_revision: Union[str, Sequence[str], None] = '6eb717126b3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('launcher_name', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('launcher_logo', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'launcher_logo')
    op.drop_column('clients', 'launcher_name')
    # ### end Alembic commands ###
