"""Intital migration

Revision ID: 3d0871d00c82
Revises: 
Create Date: 2026-02-12 12:22:27.378755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3d0871d00c82'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Fill existing NULL values with defaults
    op.execute("UPDATE documents SET document_name = 'Unknown' WHERE document_name IS NULL")
    op.execute("UPDATE documents SET content = '' WHERE content IS NULL")
    # For embedding, we can't easily fake a vector, but if it's NULL we might need to delete or ignore.
    # Assuming we can just set a dummy empty array for now or delete bad rows.
    # Let's delete rows with null embedding as they are useless for RAG.
    op.execute("DELETE FROM documents WHERE embedding IS NULL")

    op.alter_column('documents', 'document_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('documents', 'embedding',
               existing_type=sa.ARRAY(sa.Float()),
               nullable=False)
    op.alter_column('documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('documents', 'embedding',
               existing_type=sa.ARRAY(sa.Float()),
               nullable=True)
    op.alter_column('documents', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('documents', 'document_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
