"""add file_hash to documents

Revision ID: 4d64e619d44a
Revises: 3d0871d00c82
Create Date: 2026-02-12 23:34:18.853526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d64e619d44a'
down_revision: Union[str, Sequence[str], None] = '3d0871d00c82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'file_hash')
    # ### end Alembic commands ###
