"""seat plan cache for on-demand seat plan minting

Extra operator seats used to bill against ONE Razorpay plan pinned in the
environment (``RAZORPAY_SEAT_PLAN_ID``). Razorpay plans are immutable and a
plan's amount IS the debit, so changing the seat price meant minting a plan by
hand in the dashboard and repointing that variable in lockstep — and missing the
second half left the console quoting one price while the mandate collected
another. It also made a discounted seat unbillable: the pinned plan had exactly
one amount.

This table lets the seat plan be minted on demand and reused, keyed on the
CHARGED amount (GST inclusive) rather than the base, so a price change, a new
discount or a GST-rate change each resolve to a different row and mint once.

Written by hand rather than autogenerated: the table already existed in the
local development database (a test run had created it through
``Base.metadata.create_all``), so ``alembic revision --autogenerate`` compared
model to database, found no difference, and emitted an empty upgrade.

Revision ID: 6af9910c242d
Revises: l6a7b8c9d0e1
Create Date: 2026-08-31 14:00:28.378955
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6af9910c242d"
down_revision: str | Sequence[str] | None = "l6a7b8c9d0e1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ``checkfirst`` via a guard rather than a raw CREATE: the development
    # database already holds this table, and a bare create would fail there
    # while succeeding in production.
    bind = op.get_bind()
    if sa.inspect(bind).has_table("seat_plan_cache"):
        return

    op.create_table(
        "seat_plan_cache",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        # A Razorpay plan's currency is fixed at creation, so the INR and USD
        # seat plans for one amount are different objects and must not share a
        # row. Sharing one would bill an international customer in rupees.
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default="INR",
            nullable=False,
        ),
        # Minor units in ``currency``, GST INCLUSIVE — what Razorpay debits.
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("razorpay_plan_id", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("currency", "amount_minor", name="uq_seat_plan_amount"),
        sa.CheckConstraint("amount_minor > 0", name="chk_seat_plan_amount_positive"),
    )


def downgrade() -> None:
    """Downgrade schema.

    Dropping this loses the mapping from a charged amount to the Razorpay plan
    minted for it. Nothing breaks: the next seat checkout mints a fresh plan for
    the same amount. Existing seat mandates are unaffected, because a Razorpay
    subscription references its plan directly and never reads this table.
    """
    op.drop_table("seat_plan_cache")
