"""added BANT column

Revision ID: 6eb717126b3f
Revises: 911b4b55a04a
Create Date: 2026-03-17 11:29:15.194794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6eb717126b3f'
down_revision: Union[str, Sequence[str], None] = '911b4b55a04a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('bant_need', sa.Text(), nullable=True))
    op.add_column('chat_sessions', sa.Column('bant_timeline', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('bant_authority', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('bant_budget', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'bant_budget')
    op.drop_column('chat_sessions', 'bant_authority')
    op.drop_column('chat_sessions', 'bant_timeline')
    op.drop_column('chat_sessions', 'bant_need')
    # ### end Alembic commands ###
