"""add_zcal_url_and_meeting_provider_to_bots

Revision ID: 863170bc427c
Revises: c3d4e5f6a7b8
Create Date: 2026-04-16 14:48:54.401172

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "863170bc427c"
down_revision: str | Sequence[str] | None = "c3d4e5f6a7b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bots", sa.Column("meeting_provider", sa.String(), nullable=True))
    op.add_column("bots", sa.Column("zcal_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bots", "zcal_url")
    op.drop_column("bots", "meeting_provider")
    # ### end Alembic commands ###
