"""added website column

Revision ID: 911b4b55a04a
Revises: f0e1a0080800
Create Date: 2026-03-11 15:38:11.818391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911b4b55a04a'
down_revision: Union[str, Sequence[str], None] = 'f0e1a0080800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'website')
    # ### end Alembic commands ###
