"""Create operator_expo_push_tokens (and merge heads)

The earlier revision ``c8ed5bc1ce2a`` was named "Add OperatorExpoPushToken"
but its autogenerated body only altered ``email_suppressions`` — the table was
never created by a migration. Environments that rely on alembic (production)
were therefore missing ``operator_expo_push_tokens`` entirely, and the app's
startup ``Base.metadata.create_all`` was left emitting the raw ``CREATE TABLE``
that surfaced as a ProgrammingError.

This revision creates the table to match ``models.OperatorExpoPushToken``. It
is idempotent: on any environment where ``create_all`` already built the table
(e.g. local dev) the guard turns the whole upgrade into a no-op, so it is safe
to run everywhere.

It also converges the two open heads (``d3a71b6c04e2`` and ``e7a4c2f19d80``)
into a single head so ``alembic upgrade head`` is unambiguous again.

Revision ID: a7f3c1e94b26
Revises: e7a4c2f19d80, b7c31f0a49de
Create Date: 2026-08-10

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import context, op

# revision identifiers, used by Alembic.
revision: str = "a7f3c1e94b26"
down_revision: str | Sequence[str] | None = ("e7a4c2f19d80", "b7c31f0a49de")
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLE = "operator_expo_push_tokens"


def _table_exists() -> bool:
    """True when the table is already present. Online mode introspects the live
    DB; offline (``--sql``) mode can't introspect a mock connection, so we treat
    the table as absent and emit the CREATE unconditionally into the script."""
    if context.is_offline_mode():
        return False
    return sa.inspect(op.get_bind()).has_table(TABLE)


def upgrade() -> None:
    """Create the table if it does not already exist."""
    if _table_exists():
        # Already present (e.g. built by an earlier create_all run). No-op.
        return

    op.create_table(
        TABLE,
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("client_id", sa.Integer(), nullable=True),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token", name="uq_operator_expo_push_token"),
        sa.CheckConstraint(
            "((operator_id IS NULL)::int + (client_id IS NULL)::int) = 1",
            name="chk_expo_push_token_owner_xor",
        ),
        sa.ForeignKeyConstraint(["operator_id"], ["operators.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["client_id"], ["clients.id"], ondelete="CASCADE"),
    )
    # Per-column indexes mirror ``index=True`` on the model's FK columns.
    op.create_index(
        op.f("ix_operator_expo_push_tokens_operator_id"),
        TABLE,
        ["operator_id"],
    )
    op.create_index(
        op.f("ix_operator_expo_push_tokens_client_id"),
        TABLE,
        ["client_id"],
    )


def downgrade() -> None:
    """Drop the table if present."""
    if not _table_exists():
        return
    op.drop_index(op.f("ix_operator_expo_push_tokens_client_id"), table_name=TABLE)
    op.drop_index(op.f("ix_operator_expo_push_tokens_operator_id"), table_name=TABLE)
    op.drop_table(TABLE)
