"""added locations in the chat sessions

Revision ID: f0e1a0080800
Revises: 0d45d899a58c
Create Date: 2026-03-06 15:59:35.603437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e1a0080800'
down_revision: Union[str, Sequence[str], None] = '0d45d899a58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('location', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('device', sa.String(), nullable=True))
    op.add_column('chat_sessions', sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_sessions', 'last_active_at')
    op.drop_column('chat_sessions', 'device')
    op.drop_column('chat_sessions', 'location')
    # ### end Alembic commands ###
