"""visitor_intelligence

Revision ID: ff97c9d21f8a
Revises: b9d3f7a12c48
Create Date: 2026-08-08 11:39:02.202656

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ff97c9d21f8a"
down_revision: str | Sequence[str] | None = "b9d3f7a12c48"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "email_suppressions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_email_suppressions_email"), "email_suppressions", ["email"], unique=True)
    op.add_column("bots", sa.Column("followup_sending_paused", sa.Boolean(), server_default="false", nullable=True))
    op.add_column("lead_info", sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column("lead_info", sa.Column("suppression_reason", sa.String(), nullable=True))
    op.add_column("lead_info", sa.Column("is_b2b", sa.Boolean(), nullable=True))
    op.add_column("lead_info", sa.Column("is_valid_email", sa.Boolean(), nullable=True))
    op.add_column("lead_info", sa.Column("email_score", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lead_info", "email_score")
    op.drop_column("lead_info", "is_valid_email")
    op.drop_column("lead_info", "is_b2b")
    op.drop_column("lead_info", "suppression_reason")
    op.drop_column("lead_info", "metadata_json")
    op.drop_column("bots", "followup_sending_paused")
    op.drop_index(op.f("ix_email_suppressions_email"), table_name="email_suppressions")
    op.drop_table("email_suppressions")
    # ### end Alembic commands ###
