export const themeConfigs = {
    classic: {
        container: "w-full h-full md:w-[380px] md:h-[580px] md:max-h-[calc(100vh-100px)] fixed md:right-6 md:bottom-6 right-0 bottom-0 bg-[#F8F8F8] md:rounded-2xl shadow-xl flex flex-col overflow-hidden border border-[#BBE7FF]/30 z-[9999]",
        header: "bg-[#F8F8F8] px-5 py-2 flex items-center justify-between shrink-0",
        messagesArea: "flex-1 overflow-y-auto px-5 py-4 bg-[#F8F8F8] flex flex-col gap-5",
        userBubble: "text-[#16202C] rounded-2xl",
        userBubbleDefaultBg: "#DBE9FF",
        botText: "text-[#16202C] leading-relaxed",
        inputArea: "px-4 pb-3 pt-2 bg-[#F8F8F8] shrink-0",
        inputBg: "bg-white border border-[#BBE7FF]/40 focus:border-[#BBE7FF] text-[#16202C] placeholder:text-gray-400",
        sendBtn: "text-[#BBE7FF] hover:text-[#16202C]",
        sendBtnActive: "text-[#16202C]",
    },
    modern: {
        container: "w-full h-full md:w-[380px] md:h-[580px] md:max-h-[calc(100vh-100px)] fixed md:right-6 md:bottom-6 right-0 bottom-0 bg-[#0F172A]/95 backdrop-blur-xl md:rounded-2xl shadow-[0_0_50px_-12px_rgba(37,99,235,0.4)] flex flex-col overflow-hidden border border-white/10 z-[9999]",
        header: "bg-[#0F172A] px-5 py-2 flex items-center justify-between shrink-0 border-b border-white/10",
        messagesArea: "flex-1 overflow-y-auto px-5 py-4 bg-transparent flex flex-col gap-5",
        userBubble: "text-white rounded-2xl",
        userBubbleDefaultBg: "#2563EB",
        botText: "text-gray-200 leading-relaxed",
        inputArea: "px-4 pb-3 pt-2 bg-transparent shrink-0",
        inputBg: "bg-white/5 border border-white/10 focus:border-[#2563EB] text-white placeholder:text-white/40",
        sendBtn: "text-white/40 hover:text-white",
        sendBtnActive: "text-white",
    },
    minimalist: {
        container: "w-full h-full md:w-[380px] md:h-[580px] md:max-h-[calc(100vh-100px)] fixed md:right-6 md:bottom-6 right-0 bottom-0 bg-white md:rounded-2xl shadow-lg flex flex-col overflow-hidden border border-gray-200 z-[9999]",
        header: "bg-white px-5 py-2 flex items-center justify-between shrink-0 border-b border-gray-200",
        messagesArea: "flex-1 overflow-y-auto px-5 py-4 bg-white flex flex-col gap-6",
        userBubble: "text-white rounded-2xl",
        userBubbleDefaultBg: "#111827",
        botText: "text-gray-700 leading-relaxed",
        inputArea: "px-4 pb-3 pt-2 bg-white shrink-0",
        inputBg: "bg-gray-50 border border-gray-200 focus:border-gray-400 text-gray-900 placeholder:text-gray-400",
        sendBtn: "text-gray-400 hover:text-gray-900",
        sendBtnActive: "text-gray-900",
    }
};
